server:
  port: ${PORT:${SERVER_PORT:8082}}

spring:
  application:
    name: petshop-commerce-service
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/petshop}
    username: ${SPRING_DATASOURCE_USERNAME:petshop}
    password: ${SPRING_DATASOURCE_PASSWORD:petshop}
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        default_schema: commerce
        format_sql: true
  flyway:
    enabled: true
    default-schema: commerce
    schemas: commerce

management:
  endpoints:
    web:
      exposure:
        include: health,info
